export const OUTPUT_CHANGED = "OUTPUT_CHANGED";
export const INPUT_CHANGED = "INPUT_CHANGED";
export const ERROR_CHANGED = "ERROR_CHANGED";
export const BTN_CLICKED = "BTN_CLICKED";
export const CALCULATE = "CALCULATE";
